def show_some(dealer_hand, player_hand):
    print()
    print('=' * 20)
    print("   Dealer's hand")
    print('=' * 20)
    print()
    print('< Hidden Card >')
    print(dealer_hand.cards[1])
    print()
    print('=' * 20)
    print("   Player's Hand")
    print('=' * 20)
    print()
    for card in player_hand.cards:
        print(card)
def show_all(dealer_hand, player_hand):
    print()
    print('=' * 20)
    print("   Dealer's hand")
    print('=' * 20)
    print()
    for card in dealer_hand.cards:
        print(card)
    print()
    print('=' * 20)
    print("   Player's Hand")
    print('=' * 20)
    print()
    for card in player_hand.cards:
        print(card)
def player_busts(chips):
    print()
    print('=' * 30)
    print('  Player Busts! Dealer wins!')
    print('=' * 30)
    print()
    chips.lose_bet()
def dealer_busts(chips):
    print()
    print('=' * 30)
    print('  Dealer Busts Player Wins!')
    print('=' * 30)
    print()
    chips.add_winnings()
def player_wins(chips):
    print()
    print('=' * 20)
    print('     Player Wins!')
    print('=' * 20)
    print()
    chips.add_winnings()
def dealer_wins(chips):
    print()
    print('=' * 20)
    print('     Dealer Wins!')
    print('=' * 20)
    print()
    chips.lose_bet()
def push(chips):
    print()
    print('=' * 20)
    print('       Push')
    print('=' * 20)
    print()
    chips.return_bet()